inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "acceptance/**/*"
    - "integration/**/*"
    - "google-cloud-trace.gemspec"
    - "Rakefile"
    - "support/**/*"
    - "test/**/*"

Documentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false
Lint/RescueException:
  Exclude:
    - "lib/google/cloud/trace/rails.rb"
Metrics/BlockLength:
  Exclude:
    - "lib/google-cloud-trace.rb"
Metrics/ClassLength:
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/google-cloud-trace.rb"
Naming/RescuedExceptionsVariableName:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false

# Style/StringLiterals:
#   EnforcedStyle: double_quotes
# Style/MethodDefParentheses:
#   EnforcedStyle: require_no_parentheses
# Style/HashSyntax:
#   Exclude:
#     - "lib/google/cloud/trace/v1/**/*"
# Style/NumericLiterals:
#   Enabled: false
# Style/ClassVars:
#   Enabled: false
# Style/TrivialAccessors:
#   Enabled: false
# Style/CaseEquality:
#   Enabled: false
# Style/GuardClause:
#   Enabled: false
# Metrics/CyclomaticComplexity:
#   Max: 10
# Metrics/PerceivedComplexity:
#   Max: 10
# Metrics/AbcSize:
#   Max: 25
# Metrics/ClassLength:
#   Enabled: false
# Metrics/MethodLength:
#   Max: 20
#   Exclude:
#     - "lib/google/cloud/trace/v1/**/*"
# Metrics/LineLength:
#   Exclude:
#     - "lib/google/cloud/trace/v1/**/*"
# Metrics/ParameterLists:
#   Enabled: false
# Lint/RescueException:
#   Exclude:
#     - "lib/google/cloud/trace/rails.rb"
# Layout/EmptyLineAfterGuardClause:
#   Enabled: false
# Layout/EmptyLines: # for the extra line between copyright and code
#   Enabled: false
