inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "acceptance/**/*"
    - "integration/**/*"
    - "google-cloud-debugger.gemspec"
    - "Rakefile"
    - "support/**/*"
    - "test/**/*"
    - "tmp/**/*"

Documentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false
Layout/SpaceInsideStringInterpolation:
  Enabled: false
Lint/UnifiedInteger:
  Exclude:
    - "lib/google/cloud/debugger/breakpoint/evaluator.rb"
Lint/InheritException:
  Exclude:
    - "lib/google/cloud/debugger/breakpoint/evaluator.rb"
Metrics/BlockLength:
  Exclude:
    - "lib/google-cloud-debugger.rb"
Metrics/ClassLength:
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/google-cloud-debugger.rb"
Style/ConditionalAssignment:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
